#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Brendon Bown"
email = "brendon@careweather.com"

[ui]
diff-editor = ":builtin"

[ui.movement]
edit = true

[git]
sign-on-push = true

[signing]
backend = "gpg"
key = "7D4E16BD6B75865D"
behavior = "own"
